spring:
  application:
    name: cv-analyzer

  # Database
  datasource:
      url: jdbc:postgresql://localhost:5432/cv_analyzer_db
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # Migration
  flyway:
    enabled: true

  # Ollama Ai
  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      chat:
        model: llama3.2
        options:
          temperature: 0.3

  # Upload
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size: 10MB